workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: 3.24.0
      xcode: 16.0
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.dakar301.dakar301
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Build iOS Release
        script: |
          flutter build ios --release
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -archivePath build/Runner.xcarchive archive
          xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist /Users/builder/export_options.plist -exportPath build/ipa
    artifacts:
      - ios/build/ipa/*.ipa
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
