workflows:
  android-workflow:
    name: Android Release Build
    max_build_duration: 60
    instance_type: linux
    environment:
      flutter: 3.24.0
      java: 17
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - sebastien@bestophe.com

  ios-workflow:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      flutter: 3.24.0
      xcode: 16.0
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.dakar301.dakar301
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Build iOS IPA
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
