workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: 3.24.0
      xcode: 15.4
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.dakar301.dakar301
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS app
        script: |
          flutter build ipa --release --no-codesign
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Re-sign and package
        script: |
          xcode-project build-ipa --workspace ios/Runner.xcworkspace --scheme Runner
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
